### ISSUE TITLE
Illegal instruction on raspberry pi zero w

### ISSUE THREAD

**Issue by Lalavava** [bell-sw/Liberica#1]
bellsoft-jdk10.0.2-linux-arm32-vfp-hflt.tar.gz
bellsoft-jre10.0.2-linux-arm32-vfp-hflt.tar.gz

**Comment by bell-sw** [comment]
Hi,
Thanks for the input! We support currently only Raspberry Pi 2 and 3. Raspberry Pi Zero works on BCM2835 CPU - it requires a separate build. We are working on it.

**Comment by jschwartzenberg** [comment]
Any news on a build for the Pi 1? I'd be interested in such a build as well.

**Comment by Abu-Abdullah** [comment]
facing the same issue with bellsoft-jdk14.0.1+8-linux-arm32-vfp-hflt

it is not working with Pi zero

is there a plan for this arch.
