### ISSUE TITLE
OpenJDK 13 relese artifacts on GitHub

### ISSUE THREAD

**Issue by raydac** [bell-sw/Liberica#10]
are there plans to public OpenJDK 13 release artifacts among GitHub repository releases?

**Comment by bell-sw** [comment]
Thank you for letting us know the github mirror is used. Here is the JDK 13 release: [https://github.com/bell-sw/Liberica/releases/tag/13.0.0](https://github.com/bell-sw/Liberica/releases/tag/13.0.0)
