### ISSUE TITLE
Publish on ghcr.io too

### ISSUE THREAD

**Issue by EugenMayer** [bell-sw/Liberica#105]
It would be awesome to see those issues on the gihub registry too. This avoids all those pull rate limits for all of use building on top of this great base image! Thanks!

**Comment by voitylov** [comment]
thanks for the suggestion, we are evaluating when we'd be able to deliver that now.

**Comment by voitylov** [comment]
Liberica JDK is now available in Dockerhub, GHCR, and MCR: https://bell-sw.com/libericajdk-containers/#ghcr-images

**Comment by EugenMayer** [comment]
Thank you!
