### ISSUE TITLE
JAVA_HOME value is incorrect for bellsoft/liberica-native-image-kit-container:jdk-17-nik-22-musl

### ISSUE THREAD

**Issue by udaychandra** [bell-sw/Liberica#106]
Downloaded `bellsoft/liberica-native-image-kit-container:jdk-17-nik-22-musl` image and the JAVA_HOME is pointing to an invalid location. As a workaround, I am explicitly specifying JAVA_HOME to `/usr/lib/jvm/liberica-nik-22-17`

**Comment by kholmanskikh** [comment]
Hello @udaychandra 

Thank you for reporting.

We uploaded new versions of images with a fix addressing this issue. 

Now JAVA_HOME points to the correct directory, and we also no longer add $JAVA_HOME/bin to $PATH as it's not required as NIK apk packages make correct symlinks to `java` and `native-image` anyway.

Could you please check it on your side?

Thanks.

**Comment by udaychandra** [comment]
Awesome. Thank you for the quick turnaround. If we all had [UKey](https://ukey.co) right now, I’d send you a micro tip for your time 🙂
