### ISSUE TITLE
For the newest version java -version does not mention Bellsoft or Liberica, yet it's used, right?

### ISSUE THREAD

**Issue by mavavilj** [bell-sw/Liberica#108]
For the newest version java -version does not mention Bellsoft or Liberica, yet it's used, right?

Based on:

[www.wengnermiro.com/2019/01/installing-liberica-jdk-1102-jdk-on.html](www.wengnermiro.com/2019/01/installing-liberica-jdk-1102-jdk-on.html)

I thought I would see:

openjdk version "11.0.2-BellSoft" 2018-10-16
OpenJDK Runtime Environment (build 11.0.2-BellSoft+7)
OpenJDK Server VM (build 11.0.2-BellSoft+7, mixed mode)

But I see:

openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment (build 11.0.17+7-LTS)
OpenJDK 64-Bit Server VM (build 11.0.17+7-LTS, mixed mode)

while for the Ubuntu "stock" OpenJDK I see:

openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu220.04, mixed mode, sharing)

**Comment by voitylov** [comment]
Yes, this is correct. Some applications are very sensitive to the format of this string, so we decided to make it as stock as possible. You can query java.vendor system property or inspect

java -XshowSettings:system -version

output. It should say "BellSoft".

**Comment by mavavilj** [comment]
> java -XshowSettings:system -version
> Operating System Metrics:
>     Provider: cgroupv1
>     Effective CPU Count: 8
>     CPU Period: 100000us
>     CPU Quota: -1
>     CPU Shares: -1
>     List of Processors, 8 total: 
>     0 1 2 3 4 5 6 7 
>     List of Effective Processors, 8 total: 
>     0 1 2 3 4 5 6 7 
>     List of Memory Nodes, 1 total: 
>     0 
>     List of Available Memory Nodes, 1 total: 
>     0 
>     Memory Limit: Unlimited
>     Memory Soft Limit: Unlimited
>     Memory & Swap Limit: Unlimited
>     Maximum Processes Limit: Unlimited
> 
> openjdk version "11.0.17" 2022-10-18 LTS
> OpenJDK Runtime Environment (build 11.0.17+7-LTS)
> OpenJDK 64-Bit Server VM (build 11.0.17+7-LTS, mixed mode)
>

**Comment by voitylov** [comment]
That's because I can't copy-paste properly :) Please try this:

jdk-11.0.17/bin/java -XshowSettings:all -version
