### ISSUE TITLE
Fix download URLs for version 13

### ISSUE THREAD

**Issue by byumov** [bell-sw/Liberica#11]
Hi! 

Could you please fix links for version 13, like version 12 and all other versions?

Correct links format examples:
https://github.com/bell-sw/Liberica/releases/download/12/bellsoft-jdk12-linux-amd64.deb
https://github.com/bell-sw/Liberica/releases/download/11.0.4/bellsoft-jdk11.0.4-linux-amd64.rpm
etc.
Also, the link from the official site has the correct format(13 and 13):
https://download.bell-sw.com/java/13/bellsoft-jdk13-linux-amd64.tar.gz

But links for version 13(both 13.0.0 and 13):
https://github.com/bell-sw/Liberica/releases/download/13.0.0/bellsoft-jdk13-linux-amd64-lite.deb

It could break some scripts.

Thank you!

**Comment by morgion** [comment]
Hi,

Thank you for catching this. I've updated the release - you can use updated paths:
https://github.com/bell-sw/Liberica/releases/download/13/bellsoft-jdk13-linux-amd64-lite.deb

Thanks!
