### ISSUE TITLE
Where is the Linux amd64 standalone download?

### ISSUE THREAD

**Issue by beew** [bell-sw/Liberica#110]
Hi, I am trying to get the full jdk for Linux amd64 standalone binaries from https://bell-sw.com/pages/downloads/
but can't find it anymore. The download option was there just a few days ago, what happened?

I just need it to run one app, the standalone version is ideal as I can simply link to it. I don't need java 8 to be installed system wide with the apt repository and have to to do an update-alternatives every time when I use the app. 

Thanks.

**Comment by voitylov** [comment]
That's odd. Is this not how the "Package" menu looks like for you?

![Untitled](https://user-images.githubusercontent.com/29578436/211832556-612dbc6e-8643-4bb4-a7ec-f0a35c9b04a9.png)

**Comment by beew** [comment]
HI,

Strange. It wasn't like that when I tried to download a few hours ago. It had only standard and lite. Now it is normal.

Thanks.
