### ISSUE TITLE
API: sha1 mismatch with bellsoft-jdk17.0.6+10-macos-aarch64-full.zip

### ISSUE THREAD

**Issue by yopox** [bell-sw/Liberica#111]
The following request https://api.bell-sw.com/v1/liberica/releases?version-modifier=latest&version-feature=17&os=macos&package-type=zip&bundle-type=jdk-full&arch=arm returns:

```json
[
  {
    [...]
    "downloadUrl": "https://github.com/bell-sw/Liberica/releases/download/17.0.6+10/bellsoft-jdk17.0.6+10-macos-aarch64-full.zip",
    [...]
    "version": "17.0.6+10",
    "sha1": "4eab271b04af99ca6c3868edd892937affbf83dd",
    "filename": "bellsoft-jdk17.0.6+10-macos-aarch64-full.zip",
    "installationType": "archive",
    "size": 283327726,
    [...]
  }
]
```

When downloading the file there is sha1 mismatch: actual `d1dea8062a6c9403867c1962b6483448dee6ee51` vs promised `4eab271b04af99ca6c3868edd892937affbf83dd`.

When downloaded from https://download.bell-sw.com/java/17.0.6+10/bellsoft-jdk17.0.6+10-macos-aarch64-full.zip the sha1 is correct.

**Comment by morgion** [comment]
Hi, thanks for catching this!
We have updated github, this is now consistent across github and download.
