### ISSUE TITLE
Latest Liberica NIK not yet available via SDKMAN

### ISSUE THREAD

**Issue by dr-eme** [bell-sw/Liberica#115]
While the latest releases of Liberica JDK werr made available to be installed from SDKMAN already, unfortunately Liberica NIK released last week are not there yet.

In the future, new releases should be made available on SDKMAN on the same day of release if possible.

**Comment by strizhik** [comment]
Liberica NIK appears in sdkman through a quite complex chain:
Bellsoft Product discovery API <- Foojay disco API <- SDKman.

Unfortunately we are only responsible for our API : https://api.bell-sw.com/v1/nik/releases?version=22.3.1+1
Theoretically this process should work automatically but sometimes something goes wrong. I will ping authors of disco api to fix the issue.

**Comment by dr-eme** [comment]
Copy, thanks for the description of the chain.
I've open a ticket on foojay.io's disco API for them to have a look.
https://github.com/foojayio/discoapi/issues/69

**Comment by dr-eme** [comment]
The issue in Disco API has been solved, and now the latest releases are available.
