### ISSUE TITLE
API: sha1 mismatch with bellsoft-jdk8u362+9-windows-amd64-full.zip

### ISSUE THREAD

**Issue by yopox** [bell-sw/Liberica#127]
In the [following release](https://github.com/bell-sw/Liberica/releases/tag/8u362%2B9):
`sha1sum.txt` -> `4a8e94b24d205273ea079c04fa363e5288ee1e4e`
`bellsoft-jdk8u362+9-windows-amd64-full` -> `363603114c248c6b27e86603b34a1035847d6337`

It looks like windows builds were updated yesterday but `sha1sum.txt` wasn't.

**Comment by morgion** [comment]
Thanks for catching this. Inconsistency is fixed, all is up to date.
