### ISSUE TITLE
[Web side/documentation] Install Liberica via scoop.sh on Windows 10!

### ISSUE THREAD

**Issue by hrstoyanov** [bell-sw/Liberica#15]
Can you please update the web site and point users to a new way to install Liberica jdks on Windows 10 with [scoop](scoop.sh). Scoop is new, awesome, and equivalent to ```brew``` on MacOS and (installed) works like this:

```scoop install liberica13```

Also, see this related [issue](https://github.com/ScoopInstaller/Java/issues/123)

**Comment by voitylov** [comment]
Good idea, will do. Thank you for driving this.

**Comment by hrstoyanov** [comment]
@voitylov See https://github.com/ScoopInstaller/Java/issues/123

**Comment by voitylov** [comment]
thanks. We'll take care of switching scoop over to the API version a little later.

**Comment by voitylov** [comment]
The website now includes instructions for scoop.
