### ISSUE TITLE
Using PGO Instrumentation and G1C via the (new) GraalVM distribution

### ISSUE THREAD

**Issue by spockz** [bell-sw/Liberica#150]
Reading the [blog post on the new GraalVM distributions](https://medium.com/graalvm/a-new-graalvm-release-and-new-free-license-4aab483692f5) I was excited to be able to use the newly available features PGO and G1. However, when I try to use `--pgo-instrument` in the Buildpack used by Spring Boot Native, I get an error that the flag is not recognised.

Reading the license it appears that the new GraalVM distribution should be usable by Liberica,   https://www.oracle.com/downloads/licenses/graal-free-license.html.

Is it possible to use the new GraalVM distribution with the Liberica build packs or do we need to somehow create a separate build pack?

**Comment by voitylov** [comment]
Liberica NIK (the GraalVM-based distribution from BellSoft) is based on GraalVM Community Edition (OSS), which does not have PGO and G1 GC features. Those features are only available in the Oracle GraalVM.

We are working hard to bring a ParallelGC implementation [1] into the OSS version of GraalVM Community Edition. Meanwhile, ParallelGC is already available in the Liberica NIK distribution [2].

[1] https://github.com/oracle/graal/pull/5362
[2] https://bell-sw.com/blog/new-version-of-liberica-nik-23-0-with-parallelgc-is-available/

**Comment by spockz** [comment]
Thank you for the ongoing improvements and contributing them back. I'm looking forward to testing them out.

Could you shed some light on whether it would be possible to base Liberica NIK on the new GraalVM distribution? The license seems to say it is free to use. Or is this license only applicable to the binaries Oracle provides?

**Comment by voitylov** [comment]
BellSoft Liberica NIK is OSS based on GraalVM CE. The source code of GraalVM CE does not contain PGO and G1.
Oracle GraalVM distribution is closed source and contains the improvements you mentioned.

So no, it's not possible to base our product on closed source software.

**Comment by spockz** [comment]
Thanks @voitylov. I was under the impression that the source of the enterprise edition was now also available.
