### ISSUE TITLE
Release 21.0.1+15

### ISSUE THREAD

**Issue by Mauraza** [bell-sw/Liberica#152]
Hi, in the last release, not all the tarballs are available. Are you going to release `bellsoft-jdk21.0.1+15-linux-amd64.tar.gz`?

**Comment by morgion** [comment]
Hello, 

21.0.1+15 is [Liberica JDK with CRaC
](https://bell-sw.com/blog/bellsoft-releases-liberica-jdk-lts-17-and-21-with-coordinated-restore-at-checkpoint-crac-for-fast-startup/)

If you need to check latest LTS version you can use Rest API to get latest LTS version:
https://api.bell-sw.com/v1/liberica/releases?version-modifier=latest&bitness=64&release-type=lts&os=linux&arch=x86&package-type=tar.gz&bundle-type=jdk

Documentation:
https://api.bell-sw.com/#latest-lts

**Comment by Mauraza** [comment]
Hi @morgion,

Thanks for answering!!
