### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by its-yuu** [bell-sw/Liberica#153]
does the Liberica jdk 17 LTS have the Liberica native image on its installer?
or i will explicitly install the Liberica Native image kit too?

edit: i want to use liberica openjdk plus the native image both

any answer would be appreciated thanks.

**Comment by strizhik** [comment]
Hi @its-yuu,
- Liberica JDK doesn't contain native image kit
- You should install Liberica Native Image Kit separately. You can download it from https://bell-sw.com/pages/downloads/native-image-kit/ page

**Comment by its-yuu** [comment]
> Hi @its-yuu,
> 
> * Liberica JDK doesn't contain native image kit
> * You should install Liberica Native Image Kit separately. You can download it from https://bell-sw.com/pages/downloads/native-image-kit/ page

thanks @strizhik 
last question if i only install Liberica Native Image Kit would it be included the standard OpenJDK SE ?
cause when i open both the installation folder it has the same file on it.
