### ISSUE TITLE
MSI installers don't install javaw.exe when not associate .jar

### ISSUE THREAD

**Issue by yamadamn** [bell-sw/Liberica#16]
After installing without option "Associate .jar files", I have noticed that javaw.exe does not exist in the "bin" folder.

Is this by design?
Could you include javaw.exe even if I don't associate .jar files?

**Comment by voitylov** [comment]
bug acknowledged, tentatively scheduled to be fixed in the April release.

**Comment by voitylov** [comment]
Fixed in the April release.
