### ISSUE TITLE
Java for Alpine arm (32bit)

### ISSUE THREAD

**Issue by RohitKushvaha01** [bell-sw/Liberica#183]
Hello,

I noticed that Java 17 has been released for Alpine Linux on the aarch64 architecture. I am currently seeking Java 17 for an embedded Alpine Linux system running on ARMhf. Could you provide information on whether a release for ARMhf is available or, if not, guidance on how to build it from source for ARMhf?

Thank you.

**Comment by voitylov** [comment]
Back when I integrated support for musl into OpenJDK several years ago, as a smoke test I compiled and run several demos on ARM32 musl. That involved some trickery to the build system to get it to work with a cross compiler. But right now we only support x86_64 and AArch64 as primary targets for musl.
