### ISSUE TITLE
liberica docker images debian and openssl version 

### ISSUE THREAD

**Issue by chris-orchard** [bell-sw/Liberica#200]
The `liberica-openjdk-debian` and `liberica-openjre-debian` docker images are using Debian 11.

This has openssl 1.1.1w which appears to be the last freely available but has several vulnerabilites:
https://openssl-library.org/news/vulnerabilities-1.1.1/
Newer `1.1.1_` versions are listed as 'premium support'.

Are you planning to move these docker images to Debian 12? Or produce alternative new ones using 12 which is using openssl 3.x.x?

https://tracker.debian.org/pkg/openssl

**Comment by dchuyko** [comment]
You can always use `liberica-runtime-container` which is based on Alpaquita Linux that provides 3.x.x. OpenSSL is not a part of Java images in any case (but you can install it if there is a package manager, i.e. not `slim` in our case).

**Comment by morgion** [comment]
New images based on debian:12 have been uploaded to dockerhub.

**Comment by pavelbelonosov** [comment]
Hello, @morgion, are you planning to update debian version in other images (like bellsoft/liberica-openjdk-debian:17.0.11 or other). We faced an issue on  bellsoft/liberica-openjdk-debian:17 that recent devian upgrade broke our keystore generation/
