### ISSUE TITLE
scoop install liberica15 

### ISSUE THREAD

**Issue by hrstoyanov** [bell-sw/Liberica#28]
.. does not work

**Comment by den1ska** [comment]
@hrstoyanov Hristo, could you please elaborate on this?

I've just tested on my local machine and it does work.
```
PS C:\Users\denis> scoop install liberica
Installing 'liberica' (15-36) [64bit]
bellsoft-jdk15%2B36-windows-amd64.zip (178.6 MB) [============================================================] 100%
Checking hash of bellsoft-jdk15%2B36-windows-amd64.zip ... ok.
Extracting bellsoft-jdk15%2B36-windows-amd64.zip ... done.
Linking ~\scoop\apps\liberica\current => ~\scoop\apps\liberica\15-36
'liberica' (15-36) was installed successfully!
PS C:\Users\denis> java -version
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36)
OpenJDK 64-Bit Server VM (build 15+36, mixed mode, sharing)
PS C:\Users\denis>
```

**Comment by hrstoyanov** [comment]
Oh ... Maybe I used the wrong syntax?

scoop install liberica15


How do you install specific versions?

**Comment by den1ska** [comment]
As far as I know, `scoop` allows us to install only the latest versions. However, it's possible to get back to the earlier versions with using the following command:

```scoop reset liberica@14.0.2+13```

Though, it is assumed that you installed this particular version in the past.

**Comment by hrstoyanov** [comment]
Hm ...ok... I thought liberica15, liberica11 are like separate modules not
the same one, so that a user can have several versions at the same time . I
need 8,1 and 15, all liberica.

/Hristo Stoyanov

**Comment by den1ska** [comment]
Yes, you're correct, they are separate, except that the current development version (15) doesn't have a manifest with ordinal.

Here's a list of all available versions:

PS C:\Users\denis> scoop search liberica
'java' bucket:
    liberica-full-jre (15-36)
    liberica-full-lts-jre (11.0.8-10)
    liberica-full-lts (11.0.8-10)
    liberica-full (15-36)
    liberica-jre (15-36)
    liberica-lite-lts (11.0.8-10)
    liberica-lite (15-36)
    liberica-lts-jre (11.0.8-10)
    liberica-lts (11.0.8-10)
    liberica (15-36)
    liberica11-full-jre (11.0.8-10)
    liberica11-full (11.0.8-10)
    liberica11-jre (11.0.8-10)
    liberica11-lite (11.0.8-10)
    liberica11 (11.0.8-10)
    liberica12-lite (12.0.2-10)
    liberica12 (12.0.2-10)
    liberica13-full-jre (13.0.2-9)
    liberica13-full (13.0.2-9)
    liberica13-jre (13.0.2-9)
    liberica13-lite (13.0.2-9)
    liberica13 (13.0.2-9)
    liberica14-full-jre (14.0.2-13)
    liberica14-full (14.0.2-13)
    liberica14-jre (14.0.2-13)
    liberica14-lite (14.0.2-13)
    liberica14 (14.0.2-13)
    liberica8-full-jre (8u265-1)
    liberica8-full (8u265-1)
    liberica8-jre (8u265-1)
    liberica8 (8u265-1)

**Comment by voitylov** [comment]
Assume the issue is resolved now. Feel free to reopen if the issue persists.
