### ISSUE TITLE
jdk 11.0.9 from repo "https://apt.bell-sw.com/ stable main"- no ShenandoahGC

### ISSUE THREAD

**Issue by Manjago** [bell-sw/Liberica#30]
I got jdk 11.0.9 from deb [arch=amd64] https://apt.bell-sw.com/ stable main, but it has no ShenandoahGC

```
kirill@temnenkov-asus:/etc$ java --version
openjdk 11.0.9 2020-10-20 LTS
OpenJDK Runtime Environment (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM (build 11.0.9+11-LTS, mixed mode)
kirill@temnenkov-asus:/etc$ java -XX:+UseShenandoahGC
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by voitylov** [comment]
11.0.9+12 is on its way.

**Comment by Manjago** [comment]
> 11.0.9+12 is on its way.

Thanks! When can i download Liberica JDK 11.0.9+12? i only see version Liberica JDK 11.0.9+11, LTS on downloads page https://bell-sw.com/pages/downloads/#/java-11-lts

**Comment by voitylov** [comment]
It's now available on the public website.

**Comment by Manjago** [comment]
> It's now available on the public website.

the repository for ubuntu (deb [arch=amd64] https://apt.bell-sw.com/ stable main") contains the old version :-(

```
kirill@temnenkov-asus:~$ sudo apt-get remove bellsoft-java11
kirill@temnenkov-asus:~$ sudo apt-get install bellsoft-java11
kirill@temnenkov-asus:~$ java -version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM (build 11.0.9+11-LTS, mixed mode)
```

**Comment by voitylov** [comment]
Please allow a couple of hours for CDN propagation.
