### ISSUE TITLE
fatal error: unexpected tag at (methodData.cpp:1251) on 1.8.0

### ISSUE THREAD

**Issue by DonalEvans** [bell-sw/Liberica#33]
This issue has been observed twice, though it is difficult to reproduce (1 failure in 2000 runs of the test that reproduces it).

Both failures were observed on AWS i3.2xlarge instances using the following environment: 
```
OS name: Linux
Architecture: amd64
OS version: 3.10.0-1127.19.1.el7.x86_64
```
Failure 1 used Java version 1.8.0_265
Artifacts generated by the first failure are attached here:
[hs_err_pid14916.log](https://github.com/bell-sw/Liberica/files/5656033/hs_err_pid14916.log)
[replay_pid14916.log](https://github.com/bell-sw/Liberica/files/5656034/replay_pid14916.log)

Failure 2 used Java version 1.8.0_272
Artifacts generated by the second failure are attached here:
[hs_err_pid3180.log](https://github.com/bell-sw/Liberica/files/5656045/hs_err_pid3180.log)
[replay_pid3180.log](https://github.com/bell-sw/Liberica/files/5656046/replay_pid3180.log)

Both failures have the same stack trace, shown below:
```
VMError::report_and_die()+0x2e2
report_fatal(char const*, int, char const*)+0x54
MethodData::next_extra(DataLayout*)+0x85
MethodData::arg_info()+0x30
ciMethodData::update_escape_info()+0x15d
BCEscapeAnalyzer::invoke(BCEscapeAnalyzer::StateInfo&, Bytecodes::Code, ciMethod*, ciKlass*)+0x676
BCEscapeAnalyzer::iterate_one_block(ciBlock*, BCEscapeAnalyzer::StateInfo&, GrowableArray<ciBlock*>&) [clone .constprop.68]+0xccf
BCEscapeAnalyzer::iterate_blocks(Arena*)+0x4e0
BCEscapeAnalyzer::compute_escape_info()+0x576
BCEscapeAnalyzer::BCEscapeAnalyzer(ciMethod*, BCEscapeAnalyzer*)+0x2a7
BCEscapeAnalyzer::invoke(BCEscapeAnalyzer::StateInfo&, Bytecodes::Code, ciMethod*, ciKlass*)+0x676
BCEscapeAnalyzer::iterate_one_block(ciBlock*, BCEscapeAnalyzer::StateInfo&, GrowableArray<ciBlock*>&) [clone .constprop.68]+0xccf
BCEscapeAnalyzer::iterate_blocks(Arena*)+0x4e0
BCEscapeAnalyzer::compute_escape_info()+0x576
BCEscapeAnalyzer::BCEscapeAnalyzer(ciMethod*, BCEscapeAnalyzer*)+0x2a7
BCEscapeAnalyzer::invoke(BCEscapeAnalyzer::StateInfo&, Bytecodes::Code, ciMethod*, ciKlass*)+0x676
BCEscapeAnalyzer::iterate_one_block(ciBlock*, BCEscapeAnalyzer::StateInfo&, GrowableArray<ciBlock*>&) [clone .constprop.68]+0xccf
BCEscapeAnalyzer::iterate_blocks(Arena*)+0x4e0
BCEscapeAnalyzer::compute_escape_info()+0x576
BCEscapeAnalyzer::BCEscapeAnalyzer(ciMethod*, BCEscapeAnalyzer*)+0x2a7
BCEscapeAnalyzer::invoke(BCEscapeAnalyzer::StateInfo&, Bytecodes::Code, ciMethod*, ciKlass*)+0x676
BCEscapeAnalyzer::iterate_one_block(ciBlock*, BCEscapeAnalyzer::StateInfo&, GrowableArray<ciBlock*>&) [clone .constprop.68]+0xccf
BCEscapeAnalyzer::iterate_blocks(Arena*)+0x4e0
BCEscapeAnalyzer::compute_escape_info()+0x576
BCEscapeAnalyzer::BCEscapeAnalyzer(ciMethod*, BCEscapeAnalyzer*)+0x2a7
ciMethod::get_bcea()+0x85
ConnectionGraph::process_call_arguments(CallNode*)+0x296
ConnectionGraph::compute_escape()+0x9cc
ConnectionGraph::do_analysis(Compile*, PhaseIterGVN*)+0x11d
Compile::Optimize()+0x7f1
Compile::Compile(ciEnv*, C2Compiler*, ciMethod*, int, bool, bool, bool)+0xce2
C2Compiler::compile_method(ciEnv*, ciMethod*, int)+0xa3
CompileBroker::invoke_compiler_on_method(CompileTask*)+0x72c
CompileBroker::compiler_thread_loop()+0x6d8
JavaThread::thread_main_inner()+0xdb
JavaThread::run()+0x299
java_start(Thread*)+0x102
start_thread+0xc5
```

**Comment by voitylov** [comment]
This could be a manifestation of JDK-8216987 or something similar to JDK-8231501 (the latter may not apply to 8u, though), or both. The code in question lacks atomicity in 8u. Is there a possibility to get a test case which, with some probability, would cause the failure?

**Comment by DonalEvans** [comment]
Unfortunately, the scenario in which this issue has been observed is complex and I haven't been able to find another way to reproduce it with any reliability. I do also have a core dump for each failure available which I didn't attach, because the files are ~1.8GB, but if they would be helpful then I can find some way to provide them.

Out of curiosity, in the event that the issue is JDK-8216987 or JDK-8231501, is it likely that a fix would be made to 8u, or is the recommended remedy to move to version 11+?

**Comment by voitylov** [comment]
backport of the issues causing the crash to 8u has been initiated.

**Comment by voitylov** [comment]
Liberica 8u282 released on January 19 2021 has the four fixes affecting this crash included.
