### ISSUE TITLE
Error: --module-path is not specified and this runtime image does not contain jmods directory (FULL image target)

### ISSUE THREAD

**Issue by lospejos** [bell-sw/Liberica#34]
# Error: --module-path is not specified and this runtime image does not contain jmods directory using FULL image target

### 1.1) Loaded initial Dockerfile (*here and later '$' means non-root command prompt*):

`$ cd /opt && curl https://raw.githubusercontent.com/bell-sw/Liberica/master/docker/repos/liberica-openjdk-alpine-musl/15/Dockerfile --output ./Dockerfile`

### 1.3) Built new image using "full" target (as per https://hub.docker.com/r/bellsoft/liberica-openjdk-alpine-musl, it "can be used to create arbitrary module set, ~180 MB")

`$ docker build -t lospejos/liberica-openjdk15-alpine_latest-musl . --build-arg LIBERICA_IMAGE_VARIANT=full`

### 1.4) Got my custom image:

`$ docker images
REPOSITORY                                       TAG                 IMAGE ID            CREATED             SIZE
lospejos/liberica-openjdk15-alpine_latest-musl   latest              360d0167ee11        7 minutes ago       186MB`

### 1.5) Started Dockerized JVM:

`$ docker run --rm -it lospejos/liberica-openjdk15-alpine_latest-musl:latest sh`

Docker VM started successfully, I see command prompt.

### 2.1) Linux:

`$ uname -a
Linux 916e94ba8f16 4.19.130-boot2docker #1 SMP Mon Jun 29 23:52:55 UTC 2020 x86_64 Linux`

`$ cat /etc/*release*
3.12.3
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.3
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"`

### 2.2) Java:
`$ java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode)`

### 2.3) Prepared test class file
`$ mkdir -p /opt/a && cd /opt/a`
`$ cat > ./Test.java << EOF
class Test {
    public static void main(String[] args) {
        System.out.println("Test");
    }
}
EOF`

### 2.4) Successfully compiled and ran it:

`$ javac ./Test.java`
`$ java Test
Test`

### 2.5) List modules required by this class:

`$ jdeps --print-module-deps Test.class > ./java.modules`

`$ cat ./java.modules
java.base`

### 2.6) Trying to build customized Java runtime to include only this module:

`$ jlink --verbose --compress 2 --strip-debug --no-header-files --no-man-pages --add-modules $(cat java.modules) --output /opt/java-min`

Expected to get minimal java runtime in /opt/java-min, but actually got an error:

`Error: --module-path is not specified and this runtime image does not contain jmods directory.
Usage: jlink <options> --module-path <modulepath> --add-modules <module>[,<module>...]
Use --help for a list of possible options`

Please assist. Thanks.

**Comment by den1ska** [comment]
Thank you for spotting this. We made all the necessary changes in the Dockerfiles and now if you build a `standard` image you will get all jmods inside the image. Please note that we've renamed `full` to `standard` to align image variant names with the used JDK bundles.

**Comment by lospejos** [comment]
You guys are awesome! Thanks for a quick response!
