### ISSUE TITLE
LibericaFX for embedded

### ISSUE THREAD

**Issue by jsixface** [bell-sw/Liberica#36]
Hello, 
I tried the `aarch64` version of jdk-11-full build on board with Freescale i.MX 8M processor. It looks like the `monocle` implementation for glass is not included with the bundle. 
Is there a plan to include monocle in the future ?

**Comment by JRcleghorn** [comment]
Hi-

we plan to add support for native egl rendering for the R Pi in the public binaries. Others (like the production platform mentioned in the bug) are on a case-by-case basis for a specific customer.

Would it be possible to connect you with our engineering team next week?
