### ISSUE TITLE
JRE 15.0.2+10, JavaFx, embedded ARM Raspberry Pi 3: setting opacity(0) fails when using hardware accelerated pipeline

### ISSUE THREAD

**Issue by freddieFishCake** [bell-sw/Liberica#41]
Hi,
Firstly many, many thanks for Liberica JDK/JRE 15 full, it is awesome ;-)

I have a 'slide-show' type application that uses JavaFX transitions to blend between subsequent ImageViews in a collection - this typically runs on a Raspberry Pi 3 with the latest / updated raspberry Pi OS (formerly raspbian).
I would like to enhance the application to interleave some mp4 videos between the jpgs. Unfortunately JavaFx Media doesn't yet work for the arm / embedded / pi combination, so had to fall back to using ProcessBuilder to launch a bash shell calling the native omxplayer utility.
To clear the stage and allow the output from omxplayer to be seen I use e.g.  stage.setOpacity(0) before calling omxplayer.
This approach works if I use the software rendering pipeline (-Dprism.order=sw), but I would prefer to use the hardware accelerated pipeline (-Dprism.order=es2) because the slide transitions are so much smoother - actually the transitions are pretty much unusable with software pipeline. However, with the hw pipeline, .setOpacity(0) doesn't work, it removes e.g. ImageViews but leaves the entire screen covered in an opaque black rectangle.

Simplified code fragment:

```
    // As soon as we introduce a transition here the whole screen is obliterated for subsequent video if using hardware acceleration
    Transition t1 = getSimpleFadeIn(imageView, Duration.seconds(2));
    Transition t2 = getSimpleFadeOut(imageView, Duration.seconds(2));
    SequentialTransition st = new SequentialTransition(t1, t2);
    st.setOnFinished(new EventHandler<ActionEvent>() {
      @Override
      public void handle(ActionEvent t) {
        rootGroup.setOpacity(0);
        stage.setOpacity(0);
        // Plays a demo video file distributed with raspbian
        if (!System.getProperty("os.name").contains("Windows")) {
          OmxPlayer omxPlayer = new OmxPlayer("/opt/vc/src/hello_pi/hello_video/test.h264");
          omxPlayer.play();
        }
      }
    });
    st.play();

```
Any hints or tips much appreciated ;-)

**Comment by AlexanderScherbatiy** [comment]
Setting opacity on a Stage in Monocle on Raspberry Pi 3 is no-op because there is no a window which is drawn on a desktop.
Monocle draws a scene directly to the screen: [MonocleWindow._setAlpha()](https://github.com/openjdk/jfx/blob/ed5cfe72e0da4e4b90eb83cac7c50fe761f28c04/modules/javafx.graphics/src/main/java/com/sun/glass/ui/monocle/MonocleWindow.java#L347)

I wrote a simple sample where toggle buttons are used to set VBox and Stage opacity and run in on Rasperry Pi 3B+.
> sudo java -Dprism.verbose=true -Djavafx.platform=monocle -Dprism.verbose=es2 JavaFXSample

Setting opacity for VBox where all components are placed makes all components transparent.
Could the workaround where opacity is set not to the stage but to a pane which contains all components work for your application?

```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.ToggleGroup;
import javafx.scene.control.ToggleButton;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;


public class JavaFXSample extends Application {

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Sample");

        Label label = new Label("Set opacity:");

        ToggleButton noneOpacity = new ToggleButton("None");
        ToggleButton vboxOpacity = new ToggleButton("VBox");
        ToggleButton stageOpacity = new ToggleButton("Stage");

        ToggleGroup toggleGroup = new ToggleGroup();

        noneOpacity.setToggleGroup(toggleGroup);
        vboxOpacity.setToggleGroup(toggleGroup);
        stageOpacity.setToggleGroup(toggleGroup);
        noneOpacity.setSelected(true);

        VBox vbox = new VBox(10, label, noneOpacity, vboxOpacity, stageOpacity);

        noneOpacity.setOnAction(event -> {
            vbox.setOpacity(1.0);
            primaryStage.setOpacity(1.0);
        });

        vboxOpacity.setOnAction(event -> {
            primaryStage.setOpacity(1.0);
            vbox.setOpacity(0.3);
        });

        stageOpacity.setOnAction(event -> {
            vbox.setOpacity(1.0);
            primaryStage.setOpacity(0.3);
        });

        Scene scene = new Scene(vbox, 400, 300);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}
```

**Comment by freddieFishCake** [comment]
Thanks Alex, 
your example gave me good hints to get the transparency working for my use case.
:-)

This what worked for me:
  @Override
  public void start(Stage primaryStage) throws IOException {
    primaryStage.setTitle("Sample");
    // Even in frame buffer mode we need to set this in addition to setting the background-color style of the StackPane
    primaryStage.initStyle(StageStyle.TRANSPARENT);
    StackPane pane = new StackPane();
    // This only seems to work when combined with stage.initStyle(StageStyle.TRANSPARENT)
    pane.setStyle("-fx-background-color: transparent;");
    ImageView imageView = getTestImage();
    pane.getChildren().add(imageView);
...

**Comment by freddieFishCake** [comment]
Oops, I may have spoken too soon - I realised that my test was using the default (software) pipeline .. as soon as I switched to hardware accelerated I got the opaque black rectangle again.
I will distill the app down to the simplest possible example and get back to you.
