### ISSUE TITLE
MacOS ZIP Distribution does not provide Info.plist

### ISSUE THREAD

**Issue by delgurth** [bell-sw/Liberica#42]
While working on https://github.com/halcyon/asdf-java/issues/137 I noticed the reason that the Liberica MacOS ZIP distribution does not work with the /usr/libexec/java_home method of switching between Java versions on MacOS. If the distribution lacks the Info.plist it doesn't work.

When you install Liberica via the PKG version, you get the Info.plist.

Can you please add the Info.plist to the Liberica ZIP distributions as well? And the linked MacOS/libjli.dylib is also needed to make it fully work.

**Comment by morgion** [comment]
Hello,

The ZIP package is intended to use as is and never tested as generic application bundle.

However, you can extract correct app with all necessary files from the PKG bundle.

For example:
```
pkgutil --expand bellsoft-jre8u282+8-macos-amd64.pkg tmp
mkdir jre-app
cd jre-app
cat ../tmp/component.pkg/Payload | gunzip -dc | cpio -i
```

After unpacking, you will get the correct file structure:

```
macmini2:jre-app bellsoft$ ls
Contents
macmini2:jre-app bellsoft$ ls Contents/
Home            Info.plist      MacOS
macmini2:jre-app bellsoft$ ls Contents/MacOS/
libjli.dylib
macmini2:jre-app bellsoft$ ls Contents/Home/
ASSEMBLY_EXCEPTION      THIRD_PARTY_README      lib                     readme.txt
LICENSE                 bin                     man                     release
```

**Comment by delgurth** [comment]
Thanks for the explanation and alternative approach.

I'll see if I can get this working in the asdf-java plugin.

**Comment by breun** [comment]
All [other Java distributions I maintain for MacPorts](https://ports.macports.org/search/?selected_facets=maintainers_exact:breun&q=jdk&name=on) (Oracle JDK, Oracle OpenJDK, GraalVM, Eclipse Temurin, Azul Zulu, IBM Semeru, Amazon Corretto, Microsoft, SAP) do provide the full directory structure as expected by macOS Java tools in their `.tar.gz` distributions. If Liberica would do this as well, I could easily make this distribution available via MacPorts as well.
