### ISSUE TITLE
Instruction to install languages on Alpine don't work

### ISSUE THREAD

**Issue by nfrankel** [bell-sw/Liberica#46]
Sorry if I'm creating this issue in the wrong repo. Feel free to relocate it where appropriate.

I'm following the instructions regarding [Liberica NIK 21.0.0.2 Install Guide](https://bell-sw.com/pages/liberica_install_guide-native-image-kit-21.0.0.2/#alpine-linux) on Alpine Linux.

I'm using Docker. Here's my docker file:

```docker
FROM alpine:3

ENV GRAAL_VERSION=21.0.0.2
ENV SUFFIX=linux-x64-musl
ENV GRAAL_FOLDER=bellsoft-liberica-vm-openjdk11-${GRAAL_VERSION}
ENV GRAAL_ARCHIVE=${GRAAL_FOLDER}-${SUFFIX}

RUN wget https://download.bell-sw.com/vm/${GRAAL_VERSION}/${GRAAL_ARCHIVE}.tar.gz

RUN tar -C / -xzf ${GRAAL_ARCHIVE}.tar.gz

RUN mv ${GRAAL_FOLDER} /opt/nik
```

When I run `gu install ruby` (or whatever `gu` command), I get the following error:

```
Error loading shared library libstdc++.so.6: No such file or directory (needed by /opt/nik/bin/gu)
Error relocating /opt/nik/bin/gu: _Znam: symbol not found
Error relocating /opt/nik/bin/gu: _ZdaPv: symbol not found
```

I guess it's because Alpine uses _musl_ but GraalVM uses _glibc_. Actually, that's the reason I'm interested in NIK: I'd like to run on Alpine.

**Comment by voitylov** [comment]
We fixed this in the forthcoming release due together with April CPU. Meanwhile, please try this workaround:

apk add libstdc++

**Comment by nfrankel** [comment]
Thanks for the quick feedback

**Comment by voitylov** [comment]
Note that on Alpine libstdc++ is not installed by default. To build a mostly static image and avoid this (and other) dependencies in the generated native images a user can provide -H:+StaticExecutableWithDynamicLibC during build time.

**Comment by nfrankel** [comment]
You might have closed the bug a bit fast.

You also need to install `bash` since the Ruby `post_install_hook.sh` requires bash.

Running it causes another issue related to missing development tools. The current documentation doesn't mention anything of the sort.

**Comment by voitylov** [comment]
I guess that should complain about openssl. We definitely need a doc revamp in the area of dependencies on Alpine Linux for the various components installed through tar.gz and gu mechanism. Despite the fact we are working on packaging things into apk, there always is going to be a fraction of users who prefer tar.gz. Let's assume this issue is about that.

**Comment by nfrankel** [comment]
I'm trying to make things work right now. When it has, I'll publish the Dockerfile and will let you know about it.

**Comment by nfrankel** [comment]
Here it is:

```docker
FROM alpine:3

ENV GRAAL_VERSION=21.0.0.2
ENV SUFFIX=linux-x64-musl
ENV GRAAL_FOLDER=bellsoft-liberica-vm-openjdk11-${GRAAL_VERSION}
ENV GRAAL_ARCHIVE=${GRAAL_FOLDER}-${SUFFIX}
ENV TRUFFLERUBY_RECOMPILE_OPENSSL=false
ENV NIK_FOLDER=/opt/nik
ENV PATH=$PATH:${NIK_FOLDER}/languages/ruby/bin

RUN wget https://download.bell-sw.com/vm/${GRAAL_VERSION}/${GRAAL_ARCHIVE}.tar.gz \
 && tar -C / -xzf ${GRAAL_ARCHIVE}.tar.gz \
 && rm ${GRAAL_ARCHIVE}.tar.gz \
 && apk add libstdc++ bash --no-cache \
 && mv ${GRAAL_FOLDER} ${NIK_FOLDER} \
 && export PATH=$PATH:${NIK_FOLDER}/bin \
 && gu install ruby \
 && ${NIK_FOLDER}/languages/ruby/lib/truffle/post_install_hook.sh
```

1. The resulting image is 1.26GB
2. I skip the recompilation of Open SSL

**Comment by voitylov** [comment]
thank you Nicolas! The instructions are updated to reflect the required packages for various language plugins: https://bell-sw.com/pages/liberica_install_guide-native-image-kit-21.1.0/

**Comment by nfrankel** [comment]
I'll retry with these instructions and let you know.

**Comment by nfrankel** [comment]
It works! I don't know your workflow, do you want me to close the issue or do you want to do it?
