### ISSUE TITLE
Module jdk8internals not found in JDK 11.0.11+9 for Linux amd64

### ISSUE THREAD

**Issue by raydac** [bell-sw/Liberica#48]
I was trying to build an application with Liberica JDK 11.0.11+9 Linux amd64 but got error from jmake
```
Error: Module jdk8internals not found
```
with Liberica JDK 11.0.10+9 everything is ok
is the module officially removed since the release?

**Comment by voitylov** [comment]
JDK 11.0.11 and 11.0.10 contain identical set of modules:

```
java.base.jmod
java.compiler.jmod
java.datatransfer.jmod
java.desktop.jmod
java.instrument.jmod
java.logging.jmod
java.management.jmod
java.management.rmi.jmod
java.naming.jmod
java.net.http.jmod
java.prefs.jmod
java.rmi.jmod
java.scripting.jmod
java.se.jmod
java.security.jgss.jmod
java.security.sasl.jmod
java.smartcardio.jmod
java.sql.jmod
java.sql.rowset.jmod
java.transaction.xa.jmod
java.xml.crypto.jmod
java.xml.jmod
jdk.accessibility.jmod
jdk.aot.jmod
jdk.attach.jmod
jdk.charsets.jmod
jdk.compiler.jmod
jdk.crypto.cryptoki.jmod
jdk.crypto.ec.jmod
jdk.dynalink.jmod
jdk.editpad.jmod
jdk.hotspot.agent.jmod
jdk.httpserver.jmod
jdk.internal.ed.jmod
jdk.internal.jvmstat.jmod
jdk.internal.le.jmod
jdk.internal.opt.jmod
jdk.internal.vm.ci.jmod
jdk.internal.vm.compiler.jmod
jdk.internal.vm.compiler.management.jmod
jdk.jartool.jmod
jdk.javadoc.jmod
jdk.jcmd.jmod
jdk.jconsole.jmod
jdk.jdeps.jmod
jdk.jdi.jmod
jdk.jdwp.agent.jmod
jdk.jfr.jmod
jdk.jlink.jmod
jdk.jshell.jmod
jdk.jsobject.jmod
jdk.jstatd.jmod
jdk.localedata.jmod
jdk.management.agent.jmod
jdk.management.jfr.jmod
jdk.management.jmod
jdk.naming.dns.jmod
jdk.naming.ldap.jmod
jdk.naming.rmi.jmod
jdk.net.jmod
jdk.pack.jmod
jdk.rmic.jmod
jdk.scripting.nashorn.jmod
jdk.scripting.nashorn.shell.jmod
jdk.sctp.jmod
jdk.security.auth.jmod
jdk.security.jgss.jmod
jdk.unsupported.desktop.jmod
jdk.unsupported.jmod
jdk.xml.dom.jmod
jdk.zipfs.jmod
```

There is no module jdk8internals in either of them. jdk8internals module is a specific designation for JDK 8 internals that got removed from the JDK in an onward release, maintained here: http://hg.openjdk.java.net/jdk-updates/jdk11u/file/5a4b6a035514/langtools/src/jdk.jdeps/share/classes/com/sun/tools/jdeps/resources/jdk8_internals.txt. What you are probably hitting is different behaviour of jdeps due to https://bugs.openjdk.java.net/browse/JDK-8213909 which got back ported into 11.0.11.

Please attach the exact output of jdeps to better understand the difference in behaviour observed.

**Comment by raydac** [comment]
exactly, made comparing of build processes in my project and found interesting thing, my automatic build process make analyzing of JAR with jdeps, so that 11.0.10+9 generates
```
sciareto-1.4.12-SNAPSHOT.jar -> JDK removed internal API
sciareto-1.4.12-SNAPSHOT.jar -> java.base
sciareto-1.4.12-SNAPSHOT.jar -> java.compiler
sciareto-1.4.12-SNAPSHOT.jar -> java.datatransfer
sciareto-1.4.12-SNAPSHOT.jar -> java.desktop
sciareto-1.4.12-SNAPSHOT.jar -> java.logging
sciareto-1.4.12-SNAPSHOT.jar -> java.naming
sciareto-1.4.12-SNAPSHOT.jar -> java.prefs
sciareto-1.4.12-SNAPSHOT.jar -> java.scripting
sciareto-1.4.12-SNAPSHOT.jar -> java.sql
sciareto-1.4.12-SNAPSHOT.jar -> jdk.unsupported
sciareto-1.4.12-SNAPSHOT.jar -> not found
```
and JDK 11.0.11+9 generates
```
sciareto-1.4.12-SNAPSHOT.jar -> jdk8internals
sciareto-1.4.12-SNAPSHOT.jar -> java.base
sciareto-1.4.12-SNAPSHOT.jar -> java.compiler
sciareto-1.4.12-SNAPSHOT.jar -> java.datatransfer
sciareto-1.4.12-SNAPSHOT.jar -> java.desktop
sciareto-1.4.12-SNAPSHOT.jar -> java.logging
sciareto-1.4.12-SNAPSHOT.jar -> java.naming
sciareto-1.4.12-SNAPSHOT.jar -> java.prefs
sciareto-1.4.12-SNAPSHOT.jar -> java.scripting
sciareto-1.4.12-SNAPSHOT.jar -> java.sql
sciareto-1.4.12-SNAPSHOT.jar -> jdk.unsupported
sciareto-1.4.12-SNAPSHOT.jar -> not found
```
interesting why was changed `sciareto-1.4.12-SNAPSHOT.jar -> JDK removed internal API` to `sciareto-1.4.12-SNAPSHOT.jar -> jdk8internals` between JDK versions, is it ok?

**Comment by voitylov** [comment]
Now that the damage is done, it's hard to tell if it's best to revert the name or keep jdk8internals, one can argue both ways. I raised this on core-libs-dev: http://mail.openjdk.java.net/pipermail/core-libs-dev/2021-April/076674.html

**Comment by voitylov** [comment]
JDK-8269292, the back port to the issue that fixed the problem, is due to appear in 11.0.13.

**Comment by raydac** [comment]
looks like problem still presented in new 11.0.12+7
![image](https://user-images.githubusercontent.com/3008810/126441235-bf2a5e4d-0bf4-4a9c-b2d2-e0a33d74b080.png)

**Comment by voitylov** [comment]
This is fixed now.
