### ISSUE TITLE
MacOS/Linux brew distributions?

### ISSUE THREAD

**Issue by hrstoyanov** [bell-sw/Liberica#5]
Hello,
Are there any plans to deliver Liberica JDK as (the increasingly popular) [brew](https://brew.sh/) packages for MacOS/Linux? For example, look at the AdoptOpenJdk brew project here:

https://github.com/AdoptOpenJDK/homebrew-openjdk

**Comment by voitylov** [comment]
Yes. We'll probably get sdkman integration done first, but brew is pretty high on our priority list.

**Comment by hrstoyanov** [comment]
Thanks @voitylov that would a killer feature since MacOS uses brew and Linux is quickly adopting it ([Linux Brew](https://github.com/Linuxbrew/brew) recently merged into the parent project). Also, with Windows 10 WLS. looks like Linux brew would work on WIndows 10 as well!
I am not sure how popular SDKMAN is, maybe only windows?

**Comment by bell-sw** [comment]
Liberica JDK Homebrew Tap (Mac) can be found here: https://github.com/bell-sw/homebrew-liberica

Instructions update on the website pending.

**Comment by hrstoyanov** [comment]
Thank you! Will try in a few hours on my Mac.

**Comment by voitylov** [comment]
Linux brew formulae is provided by @ta2gch.

Website is updated: 
https://bell-sw.com/pages/java-8u212
https://bell-sw.com/pages/java-11.0.3
https://bell-sw.com/pages/java-12.0.1

announcement is out:
https://bell-sw.com/announcement/2019/05/15/dev-repositories/

**Comment by hrstoyanov** [comment]
The Mac brew worked yesterday! Nice work!
