### ISSUE TITLE
Oracle JDK/JRE registry key compatibility

### ISSUE THREAD

**Issue by CreeperKong** [bell-sw/Liberica#54]
I found that some Java exe app packed with launch4j doesnt work without these registry keys.

I have manually added these keys according to the following documentation, and it works.

[https://docs.oracle.com/javase/9/install/installation-jdk-and-jre-microsoft-windows-platforms.htm#GUID-47C269A3-5220-412F-9E31-4B8C37A82BFB](https://docs.oracle.com/javase/9/install/installation-jdk-and-jre-microsoft-windows-platforms.htm#GUID-47C269A3-5220-412F-9E31-4B8C37A82BFB) 

Hope to provide Oracle Java SE registry key compatibility support for msi package.

**Comment by CreeperKong** [comment]
Thank you, issue solved.

**Comment by strizhik** [comment]
Thanks for your feedback :)
