### ISSUE TITLE
Liberica 17.0.1 has high severity vulnerabilities with busybox

### ISSUE THREAD

**Issue by pfilaretov** [bell-sw/Liberica#66]
Hi,

I'm considering liberica 17 for production use and scanned the latest docker image with [Prisma](https://www.prismacloud.io) as a part of the corporate policy.
The scan found 9 high severity vulnerabilities, and all of them are found in busybox. The scan also suggests that update from busybox 1.33.1-r3 to 1.33.1-r6 will fix all the vulnerabilities.

So, is it possible to update busybox version? Maybe it is already in the roadmap?

Thanks,
Petr

**Comment by morgion** [comment]
Hi,

Thanks for catching this issue. Liberica docker images on dockerhub are released with actual version of underlying OS image on release date. We have updated the Liberica images with the latest Alpine's updates. You can find it on dockerhub - bellsoft/liberica-openjre-alpine, bellsoft/liberica-openjre-alpine-musl, bellsoft/liberica-openjdk-alpine, bellsoft/liberica-openjdk-alpine-musl.

If you have further questions how to secure the supported docker images, please contact us at info@bell-sw.com
