### ISSUE TITLE
JDK release API

### ISSUE THREAD

**Issue by srbala** [bell-sw/Liberica#67]
Team,

Is there any API url available to check the releases similar to https://app.swaggerhub.com/apis-docs/azul/zulu-download-community/1.0#/
 or https://api.adoptopenjdk.net/q/swagger-ui/

**Comment by voitylov** [comment]
Yes, please take a look at https://api.bell-sw.com/ and the OpenAPI specification therein.

**Comment by srbala** [comment]
@voitylov Thank you, this will help for me.

**Comment by srbala** [comment]
@voitylov is there a way to get `latest` of specific version for example LTS 11 or 8. The https://api.bell-sw.com/v1/liberica/releases?version-modifier=latest&bitness=64&release-type=lts&os=windows&arch=x86&package-type=zip&bundle-type=jdk URL always points to 17. version-modifier only seems to take `latest`

tried to pass `feature-version` as parameter api does not seems to like it.

**Comment by strizhik** [comment]
Hello @srbala !
Please try `version-feature` param.

**Comment by srbala** [comment]
Great, thanks for quick response
