### ISSUE TITLE
Lost string encoding using alpine glibc image when text in russian

### ISSUE THREAD

**Issue by Ivanbmstu** [bell-sw/Liberica#7]
Hello again!
The same application as was in issue: https://github.com/bell-sw/Liberica/issues/6
I added logging, then in musl image everythings works as expected, but glibc image lost string encodings in logs

repo to reproduce https://github.com/Ivanbmstu/bellsoft_glibc_alpine_error.git
with java 11
run glibc-alpine-build.sh to build glibc docker image with app
run musl-alpine-build.sh to build musl docker image with app

with glibc check: docker run -p 8080:8080 alpine-sb2-logback-glibc java -jar /app.jar --logging.config=/logback.groovy
with musl check: docker run -p 8080:8080 alpine-sb2-logback-musl java -jar /app.jar --logging.config=/logback.groovy

then:
curl localhost:8080 and see container stdout logs

[glibc_image_output.txt](https://github.com/bell-sw/Liberica/files/3068483/glibc_image_output.txt)
[musl_image_output.txt](https://github.com/bell-sw/Liberica/files/3068484/musl_image_output.txt)

**Comment by voitylov** [comment]
Well, this is embarrassing. Issue confirmed.

**Comment by den1ska** [comment]
Including all locales in the base image would cause the image size to grow significantly (just the common locales will take tens of MBs). It was thus decided to fix this issue by including en_US.UTF-8 in the base Liberica Alpine GLIBC image, which should suffice for most users, including non-English speakers, and fix the case the submitter of this bug report has described.

Users willing to use other locales will be granted a possibility to build a non-standard image themselves with  LANG=…. Dockerfile argument

The updated image and Dockerfile are undergoing testing and will be made available tomorrow together with the update to documentation.

**Comment by den1ska** [comment]
Fixed by 45ef80fcdf51f93c05d86653ddd5a35e11c122a8.
