### ISSUE TITLE
DNS errors on alpine 3.13 & 3.14

### ISSUE THREAD

**Issue by sergey-volkov-lm** [bell-sw/Liberica#72]
Hello! 
Using liberica-openjdk-alpine:11.0.11, _sometimes_ I bump into errors `UnknownHostException`.
Turns out, the root problem is in alpine linux and/or its interop with docker.

So to reproduce error it's enough to ping or nslookup desired host from container.

Example host: `pecl.php.net`

One of issues opened in alpine: https://github.com/alpinelinux/docker-alpine/issues/185
And there are similar ones: https://github.com/alpinelinux/docker-alpine/issues?q=is%3Aissue+is%3Aopen+dns

In our deployment environment, I managed to reproduce error on two or four kubernetes clusters I have access to.
Too bad I couldn't figure out differences which cause the error. Docker version is the same everywhere.

Could you have a look?

**Comment by NadamHL** [comment]
使用3.12即可解决问题。同时检查你的coredns是否配置了，遇见AAAA请求，直接回复了NXDOMAIN请求。如果是的话，新版本3.14、3.15就会出现解析失败ping: bad address '' 现象

**Comment by NadamHL** [comment]
![image](https://user-images.githubusercontent.com/39847290/156514757-8a1da531-1dac-4355-a6e4-87e140ce9593.png)

**Comment by sergey-volkov-lm** [comment]
Issue seems to be no longer present thanks to alpine update in latest versions
