### ISSUE TITLE
Possibility to upgrade Alpine version for JRE 11

### ISSUE THREAD

**Issue by iromli** [bell-sw/Liberica#77]
Current `liberica-alpine-jre:11` image is based on Alpine 3.14. Is there a plan to upgrade to Alpine 3.15?

**Comment by cfredri4** [comment]
Same with all other Java versions as well. There are several CVEs fixed in Alpine 3.15

**Comment by voitylov** [comment]
The update is scheduled for next week.

**Comment by iromli** [comment]
I see that Alpine has been upgraded now. Thanks for the updates.
