### ISSUE TITLE
Can lite version use jlink?

### ISSUE THREAD

**Issue by imba-tjd** [bell-sw/Liberica#79]
I see lite version doesn't have `jmods` folder. So I guess it's expected that jlink can't find `java.base`, so that I can't use jlink to create custom jre?

**Comment by voitylov** [comment]
Lite version is a Runtime created with jlink, so you can't use it to create other Runtimes. To create a custom Runtime with a subset of modules please get the original JDK from, for example,

https://download.bell-sw.com/docker/java/11.0.14.1+1/bellsoft-jdk11.0.14.1+1-linux-amd64-lite.tar.gz

and use it to create your own Runtime. Use the Dockerfiles as guidance on how best apply jlink to get optimal size.

**Comment by imba-tjd** [comment]
Thanks for answering! I appreciate.

**Comment by diktamxx** [comment]
> Lite version is a Runtime created with jlink, so you can't use it to create other Runtimes. To create a custom Runtime with a subset of modules please get the original JDK from, for example,
> 
> https://download.bell-sw.com/docker/java/11.0.14.1+1/bellsoft-jdk11.0.14.1+1-linux-amd64-lite.tar.gz
> 
> and use it to create your own Runtime. Use the Dockerfiles as guidance on how best apply jlink to get optimal size.

Does this mean that the only way is to manually download the JDK, build it into a Docker image, and then base the new jlink (runtime) on that image? Are there any Docker images that support using jlink? Currently, I have found that bellsoft/liberica-openjdk-alpine:25 (JDK) also does not support it.🤔️
