### ISSUE TITLE
fontmanager library can not be loaded

### ISSUE THREAD

**Issue by artemy-osipov** [bell-sw/Liberica#9]
Alpine image of java 11 cannot load fontmanager library

Steps to reproduce
<img width="925" alt="Screenshot 2019-08-08 at 18 13 19" src="https://user-images.githubusercontent.com/1992775/62714986-3dbfde80-ba08-11e9-81f7-650201488842.png">

It works on adoptopenjdk alpine image
<img width="927" alt="Screenshot 2019-08-08 at 18 33 59" src="https://user-images.githubusercontent.com/1992775/62716621-1dddea00-ba0b-11e9-8e14-4ae77f9cc104.png">

**Comment by voitylov** [comment]
GLIBC embedded with this Docker image does not pick up libraries in /usr/lib by default. Could you try this as a workaround?
`apk add freetype`
`export LD_LIBRARY_PATH=/usr/lib`
`...`
Meanwhile we'll think what can be done here in general.

**Comment by artemy-osipov** [comment]
Thank you, workaround helped!

We use this image in CI and the error occurred while generating part of documentation from PlantUML (org.asciidoctor:asciidoctorj-diagram). I don't think it's such a common case to include dependency in the base image but the fact that the installed package may not be available for java is confusing.

PS actually after workaround another error occurred
```
Caused by: java.lang.NullPointerException
-- java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
```
so final solution is
```
RUN apk add --no-cache freetype ttf-dejavu
ENV LD_LIBRARY_PATH /usr/lib
```

**Comment by voitylov** [comment]
Liberica JDK for Alpine Linux now has built-in freetype. As the ttf-dejavu package increases base image size by ~20 Mb it was decided not to include it by default. For deployments which require off-screen rendering it's beneficial to build images from Dockerfile with OPT_PKGS="fontconfig ttf-dejavu" build arg.

Docs are updated to reflect the solution: https://hub.docker.com/repository/docker/bellsoft/liberica-openjdk-alpine
